# Generated by Django 3.1.7 on 2021-03-24 12:56

import app_admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_main', '0007_team_profile_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('A', 'Abandoned')], db_index=True, default='C', max_length=1)),
                ('neutral_venue', models.BooleanField(default=False)),
                ('result', models.CharField(max_length=50, validators=[app_admin.models.result_validator])),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_teams_history', to='app_main.team')),
                ('bat_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_batters', to='app_main.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_teams_history', to='app_main.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners_history', to='app_main.team')),
            ],
            options={
                'verbose_name_plural': 'IPLMatchHistory',
                'ordering': ['date'],
            },
        ),
    ]
