# Generated by Django 3.1.7 on 2021-03-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_team_profile_bg'),
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_matches', models.PositiveSmallIntegerField(default=0)),
                ('home_matches', models.PositiveSmallIntegerField(default=0)),
                ('away_matches', models.PositiveSmallIntegerField(default=0)),
                ('neutral_matches', models.PositiveSmallIntegerField(default=0)),
                ('all_wins', models.PositiveSmallIntegerField(default=0)),
                ('home_wins', models.PositiveSmallIntegerField(default=0)),
                ('away_wins', models.PositiveSmallIntegerField(default=0)),
                ('neutral_wins', models.PositiveSmallIntegerField(default=0)),
                ('bat_1st_wins', models.PositiveSmallIntegerField(default=0)),
                ('bat_2nd_wins', models.PositiveSmallIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_teams', to='app_main.team')),
                ('vs_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vs_stats_teams', to='app_main.team')),
            ],
        ),
    ]
