# Generated by Django 3.1.7 on 2021-03-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_iplstats_no_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplstats',
            name='last5_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
