# Generated by Django 3.1.7 on 2021-03-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_static'),
        ('app_admin', '0005_iplstats_last5_wins'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iplhistory',
            unique_together={('date', 'home_team', 'away_team')},
        ),
        migrations.AlterUniqueTogether(
            name='iplstats',
            unique_together={('team', 'vs_team')},
        ),
    ]
