# Generated by Django 3.1.7 on 2021-03-19 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_team_slogo'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_amt', models.FloatField(default=0)),
                ('bets_won', models.PositiveSmallIntegerField(default=0)),
                ('bets_lost', models.PositiveSmallIntegerField(default=0)),
                ('team_chgd', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app_main.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-curr_amt', 'user'],
            },
        ),
    ]
