# Generated by Django 3.1.7 on 2021-03-20 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_team_slogo'),
        ('app_users', '0003_auto_20210319_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app_main.team'),
        ),
    ]
