# Generated by Django 3.1.7 on 2021-03-31 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_auto_20210330_1442'),
        ('app_users', '0006_teamchangeaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamchangeaudit',
            name='new_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_teams', to='app_main.team'),
        ),
        migrations.AlterField(
            model_name='teamchangeaudit',
            name='old_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_teams', to='app_main.team'),
        ),
        migrations.AlterField(
            model_name='teamchangeaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
