# Generated by Django 3.1.7 on 2021-03-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_auto_20210331_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchangeaudit',
            name='amt_deducted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
