# Generated by Django 3.1.7 on 2021-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_teamchangeaudit_amt_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='curr_amt',
            field=models.FloatField(default=2000),
        ),
    ]
