# Generated by Django 3.1.7 on 2021-04-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_auto_20210401_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='curr_amt',
            field=models.FloatField(default=1700),
        ),
    ]
