# Generated by Django 3.1.7 on 2021-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-points', '-nrr', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
