# Generated by Django 3.1.7 on 2021-03-18 07:05

import app_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20210318_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='against_status',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[app_main.models.status_validator]),
        ),
        migrations.AlterField(
            model_name='team',
            name='for_status',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[app_main.models.status_validator]),
        ),
    ]
