# Generated by Django 3.1.7 on 2021-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20210318_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
