# Generated by Django 3.1.7 on 2021-03-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_team_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slogo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
