# Generated by Django 3.1.7 on 2021-03-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_team_slogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='back_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='fore_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
