# Generated by Django 3.1.7 on 2021-03-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_team_profile_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=50, unique=True)),
                ('value', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
