# Generated by Django 3.1.7 on 2021-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_auto_20210330_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='bg/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='profile_bg',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slogo',
            field=models.ImageField(blank=True, null=True, upload_to='slogo/'),
        ),
    ]
