# Generated by Django 3.1.7 on 2021-03-19 07:41

import app_matches.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_main', '0005_team_slogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(unique=True)),
                ('datetime', models.DateTimeField()),
                ('home_team_score', models.CharField(blank=True, max_length=20, null=True, validators=[app_matches.models.status_validator])),
                ('away_team_score', models.CharField(blank=True, max_length=20, null=True, validators=[app_matches.models.status_validator])),
                ('venue', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('S', 'Scheduled'), ('A', 'Abandoned')], db_index=True, default='S', max_length=1)),
                ('typ', models.CharField(choices=[('L', 'League'), ('E', 'Eliminator'), ('F', 'Final'), ('Q1', 'Qualifier1'), ('Q2', 'Qualifier2')], db_index=True, default='L', max_length=2)),
                ('home_win_pct', models.PositiveSmallIntegerField(default=0)),
                ('away_win_pct', models.PositiveSmallIntegerField(default=0)),
                ('min_bet', models.PositiveSmallIntegerField(default=20)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_teams', to='app_main.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='app_main.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='app_main.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['datetime'],
            },
        ),
    ]
