# Generated by Django 3.1.7 on 2021-03-20 11:22

import app_matches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_matches', '0002_match_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(default='Match yet to begin', max_length=50, validators=[app_matches.models.result_validator]),
        ),
    ]
