# Generated by Django 3.1.7 on 2021-03-21 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0005_team_slogo'),
        ('app_matches', '0003_auto_20210320_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amt', models.PositiveSmallIntegerField()),
                ('win_amt', models.FloatField(default=0)),
                ('lost_amt', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('P', 'Placed'), ('N', 'Not Placed'), ('D', 'Defaulted'), ('W', 'Won'), ('L', 'Lost'), ('R', 'No Result')], db_index=True, default='N', max_length=1)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.localtime)),
                ('bet_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_teams', to='app_main.team')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app_matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['match', 'create_time', 'user'],
            },
        ),
    ]
