# Generated by Django 3.1.7 on 2021-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_matches', '0004_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_amt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
