# Generated by Django 3.1.7 on 2021-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_matches', '0005_auto_20210321_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('P', 'Placed'), ('D', 'Defaulted'), ('W', 'Won'), ('L', 'Lost'), ('R', 'No Result')], db_index=True, default='P', max_length=1),
        ),
    ]
