# Generated by Django 3.1.7 on 2021-03-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_matches', '0006_auto_20210324_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_win_pct',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_win_pct',
        ),
    ]
